language: python

cache: pip

python:
- '3.5'
- '3.6-dev'
- 'nightly'

matrix:
  allow_failures:
  - python: 'nightly'

install:
- make install

script:
- make test
- make lint
- coverage run pytest_toolbox/__init__.py

after_success:
- ls -lha
- coverage combine
- bash <(curl -s https://codecov.io/bash)

deploy:
  provider: pypi
  user: samuelcolvin
  password:
    secure: "jS0D2qe3TtRMAXv1RMa8rtPY7EXZ6qOkowEZOc+MDfelMd7G7UjP+bZuLQigm0ZOW0saH3DYxlnGM+haDu6HqTHaiJmxm2UOHboZxy6kgzLP0TlR1ZQ4JQls9nwPBNJD5HSMFXYMrWCS0WrOq+DByN/NTXfnIHGasNHZ5+LKhe7aXAu0sPp1SX9MqiuPPNxVH2ujbJnvtePo0MK49el2MJFL7NYyGfCapdkZGZzZSvyeJUOCWI7XvwyojjOthHstnTlDL/Hl0+y40FdDfGEQ1Y0b2BYuciDjdMqXh9Etk1ERXJncUCKW1zMBftuzQGtODJ+R12yNMOfA0aAA4/PpptntS9qWmqax+4AatAFhWprUKKywuWIbJMJ5Kx78oejnvI7miCC/q35DLFdNyXEwZMF01uri6kJnMNw7Jawu2s1RETCltFeR//VCHW24F5oNbctjba7EkJTTFTPJ75TfyRFQfpcQ1UB58RvXdf+BqaDOtyZD1Soh+jf75z+wdt0ad0/FpXQ2uFx73+kERWWFFKNP3MLfVKgUbW5zC+oJiWIUNfgDILajYKRrF5Rar0ZmiBwQmEqTmoe2CdSQEA6j3Gy64+ovPnVmOI8yS8KFrMB4+ABc0F6wsK27RD7ZKy9bqBwvsc1tHF7l+DSHWx2yXkf0jKdbgjzhx+Qo1c5cVK0="
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.5
